name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}

      # Step 3: Run deployment commands on the VM
      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'

          # Define variables
          APP_DIR="portfolio-projects/ecomerce-app"
          REPO="https://github.com/Cypherfelix/payload-tech-ecommerce.git"
          BRANCH="main"
          ENV_CONTENT="${{ secrets.ENV_CONTENT }}"

          # Clone the repository if it doesn't exist
          if [ ! -d "$APP_DIR" ]; then
            echo "Cloning the repository..."
            git clone -b $BRANCH $REPO $APP_DIR
          fi

          echo "Setting environment variables..."

          # Navigate to the application directory
          cd $APP_DIR

          # Pull the latest changes
          echo "Pulling the latest changes..."

          git pull origin $BRANCH


          ls

          echo "Deployment complete."

          EOF
